name: Generate 3D Contribution

on:
  schedule:
    - cron: "0 0 * * *"  # chạy mỗi ngày lúc 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Profile
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate 3D Contribution Graph
        run: |
          npx github-profile-3d-contrib --username khuonglaptri3 --theme night-green

      - name: Commit & Push
        run: |
          mkdir -p profile-3d-contrib
          mv out/profile-night-green.svg profile-3d-contrib/
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update 3D Contributions"
          git push
